# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.9

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/mouworksDoc

    steps:
      - checkout

      - run:
          name: Install Vuepress
          command: sudo yarn global add vuepress

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      # - run: yarn test
      - run:
          name: Install and configure dependencies
          command: |
            git config user.email "mou.wang@g.ncu.edu.tw"
            git config user.name "mouWorks"

      - add_ssh_keys:
          fingerprints:
            - "3f:6c:81:ec:0f:b5:f7:2f:28:d5:a8:fc:e7:be:a5:18"

      - run:
          name: Testing Connect to Github
          command:  ssh -T -p 443 git@ssh.github.com

      - run :
          name: generate static docs
          command: sudo npm run deploy -y
